export type PhoneCountry = {
  iso: string
  name: string
  dial: string
}

/** ISO → emoji flag (regional indicators). */
export function isoToFlag(iso: string): string {
  const code = iso.toUpperCase()
  if (code.length !== 2) return '🌍'
  return String.fromCodePoint(...[...code].map((c) => 127397 + c.charCodeAt(0)))
}

const RAW: [string, string, string][] = [
  ['UA', 'Україна', '380'],
  ['NL', 'Netherlands', '31'],
  ['DE', 'Germany', '49'],
  ['PL', 'Poland', '48'],
  ['GB', 'United Kingdom', '44'],
  ['US', 'United States', '1'],
  ['CA', 'Canada', '1'],
  ['FR', 'France', '33'],
  ['IT', 'Italy', '39'],
  ['ES', 'Spain', '34'],
  ['PT', 'Portugal', '351'],
  ['BE', 'Belgium', '32'],
  ['AT', 'Austria', '43'],
  ['CH', 'Switzerland', '41'],
  ['SE', 'Sweden', '46'],
  ['NO', 'Norway', '47'],
  ['DK', 'Denmark', '45'],
  ['FI', 'Finland', '358'],
  ['IE', 'Ireland', '353'],
  ['CZ', 'Czechia', '420'],
  ['SK', 'Slovakia', '421'],
  ['HU', 'Hungary', '36'],
  ['RO', 'Romania', '40'],
  ['BG', 'Bulgaria', '359'],
  ['GR', 'Greece', '30'],
  ['HR', 'Croatia', '385'],
  ['SI', 'Slovenia', '386'],
  ['RS', 'Serbia', '381'],
  ['BA', 'Bosnia and Herzegovina', '387'],
  ['ME', 'Montenegro', '382'],
  ['MK', 'North Macedonia', '389'],
  ['AL', 'Albania', '355'],
  ['MD', 'Moldova', '373'],
  ['BY', 'Belarus', '375'],
  ['RU', 'Russia', '7'],
  ['KZ', 'Kazakhstan', '7'],
  ['GE', 'Georgia', '995'],
  ['AM', 'Armenia', '374'],
  ['AZ', 'Azerbaijan', '994'],
  ['TR', 'Turkey', '90'],
  ['IL', 'Israel', '972'],
  ['AE', 'United Arab Emirates', '971'],
  ['SA', 'Saudi Arabia', '966'],
  ['EG', 'Egypt', '20'],
  ['MA', 'Morocco', '212'],
  ['TN', 'Tunisia', '216'],
  ['ZA', 'South Africa', '27'],
  ['NG', 'Nigeria', '234'],
  ['KE', 'Kenya', '254'],
  ['IN', 'India', '91'],
  ['PK', 'Pakistan', '92'],
  ['BD', 'Bangladesh', '880'],
  ['CN', 'China', '86'],
  ['JP', 'Japan', '81'],
  ['KR', 'South Korea', '82'],
  ['TW', 'Taiwan', '886'],
  ['HK', 'Hong Kong', '852'],
  ['SG', 'Singapore', '65'],
  ['MY', 'Malaysia', '60'],
  ['TH', 'Thailand', '66'],
  ['VN', 'Vietnam', '84'],
  ['ID', 'Indonesia', '62'],
  ['PH', 'Philippines', '63'],
  ['AU', 'Australia', '61'],
  ['NZ', 'New Zealand', '64'],
  ['MX', 'Mexico', '52'],
  ['BR', 'Brazil', '55'],
  ['AR', 'Argentina', '54'],
  ['CL', 'Chile', '56'],
  ['CO', 'Colombia', '57'],
  ['PE', 'Peru', '51'],
  ['VE', 'Venezuela', '58'],
  ['AF', 'Afghanistan', '93'],
  ['AX', 'Åland Islands', '358'],
  ['DZ', 'Algeria', '213'],
  ['AS', 'American Samoa', '1684'],
  ['AD', 'Andorra', '376'],
  ['AO', 'Angola', '244'],
  ['AI', 'Anguilla', '1264'],
  ['AG', 'Antigua and Barbuda', '1268'],
  ['AW', 'Aruba', '297'],
  ['BS', 'Bahamas', '1242'],
  ['BH', 'Bahrain', '973'],
  ['BB', 'Barbados', '1246'],
  ['BZ', 'Belize', '501'],
  ['BJ', 'Benin', '229'],
  ['BM', 'Bermuda', '1441'],
  ['BT', 'Bhutan', '975'],
  ['BO', 'Bolivia', '591'],
  ['BQ', 'Bonaire', '599'],
  ['BW', 'Botswana', '267'],
  ['BN', 'Brunei', '673'],
  ['BF', 'Burkina Faso', '226'],
  ['BI', 'Burundi', '257'],
  ['KH', 'Cambodia', '855'],
  ['CM', 'Cameroon', '237'],
  ['CV', 'Cape Verde', '238'],
  ['KY', 'Cayman Islands', '1345'],
  ['CF', 'Central African Republic', '236'],
  ['TD', 'Chad', '235'],
  ['CX', 'Christmas Island', '61'],
  ['CC', 'Cocos Islands', '61'],
  ['KM', 'Comoros', '269'],
  ['CG', 'Congo', '242'],
  ['CD', 'Congo (DRC)', '243'],
  ['CK', 'Cook Islands', '682'],
  ['CR', 'Costa Rica', '506'],
  ['CI', "Côte d'Ivoire", '225'],
  ['CU', 'Cuba', '53'],
  ['CW', 'Curaçao', '599'],
  ['CY', 'Cyprus', '357'],
  ['DJ', 'Djibouti', '253'],
  ['DM', 'Dominica', '1767'],
  ['DO', 'Dominican Republic', '1809'],
  ['EC', 'Ecuador', '593'],
  ['SV', 'El Salvador', '503'],
  ['GQ', 'Equatorial Guinea', '240'],
  ['ER', 'Eritrea', '291'],
  ['EE', 'Estonia', '372'],
  ['SZ', 'Eswatini', '268'],
  ['ET', 'Ethiopia', '251'],
  ['FK', 'Falkland Islands', '500'],
  ['FO', 'Faroe Islands', '298'],
  ['FJ', 'Fiji', '679'],
  ['GF', 'French Guiana', '594'],
  ['PF', 'French Polynesia', '689'],
  ['GA', 'Gabon', '241'],
  ['GM', 'Gambia', '220'],
  ['GH', 'Ghana', '233'],
  ['GI', 'Gibraltar', '350'],
  ['GL', 'Greenland', '299'],
  ['GD', 'Grenada', '1473'],
  ['GP', 'Guadeloupe', '590'],
  ['GU', 'Guam', '1671'],
  ['GT', 'Guatemala', '502'],
  ['GG', 'Guernsey', '44'],
  ['GN', 'Guinea', '224'],
  ['GW', 'Guinea-Bissau', '245'],
  ['GY', 'Guyana', '592'],
  ['HT', 'Haiti', '509'],
  ['HN', 'Honduras', '504'],
  ['IS', 'Iceland', '354'],
  ['IQ', 'Iraq', '964'],
  ['IR', 'Iran', '98'],
  ['IM', 'Isle of Man', '44'],
  ['JM', 'Jamaica', '1876'],
  ['JE', 'Jersey', '44'],
  ['JO', 'Jordan', '962'],
  ['KI', 'Kiribati', '686'],
  ['KW', 'Kuwait', '965'],
  ['KG', 'Kyrgyzstan', '996'],
  ['LA', 'Laos', '856'],
  ['LV', 'Latvia', '371'],
  ['LB', 'Lebanon', '961'],
  ['LS', 'Lesotho', '266'],
  ['LR', 'Liberia', '231'],
  ['LY', 'Libya', '218'],
  ['LI', 'Liechtenstein', '423'],
  ['LT', 'Lithuania', '370'],
  ['LU', 'Luxembourg', '352'],
  ['MO', 'Macau', '853'],
  ['MG', 'Madagascar', '261'],
  ['MW', 'Malawi', '265'],
  ['MV', 'Maldives', '960'],
  ['ML', 'Mali', '223'],
  ['MT', 'Malta', '356'],
  ['MH', 'Marshall Islands', '692'],
  ['MQ', 'Martinique', '596'],
  ['MR', 'Mauritania', '222'],
  ['MU', 'Mauritius', '230'],
  ['YT', 'Mayotte', '262'],
  ['FM', 'Micronesia', '691'],
  ['MC', 'Monaco', '377'],
  ['MN', 'Mongolia', '976'],
  ['MS', 'Montserrat', '1664'],
  ['MZ', 'Mozambique', '258'],
  ['MM', 'Myanmar', '95'],
  ['NA', 'Namibia', '264'],
  ['NR', 'Nauru', '674'],
  ['NP', 'Nepal', '977'],
  ['NC', 'New Caledonia', '687'],
  ['NI', 'Nicaragua', '505'],
  ['NE', 'Niger', '227'],
  ['NU', 'Niue', '683'],
  ['NF', 'Norfolk Island', '672'],
  ['KP', 'North Korea', '850'],
  ['MP', 'Northern Mariana Islands', '1670'],
  ['OM', 'Oman', '968'],
  ['PW', 'Palau', '680'],
  ['PS', 'Palestine', '970'],
  ['PA', 'Panama', '507'],
  ['PG', 'Papua New Guinea', '675'],
  ['PY', 'Paraguay', '595'],
  ['PR', 'Puerto Rico', '1787'],
  ['QA', 'Qatar', '974'],
  ['RE', 'Réunion', '262'],
  ['RW', 'Rwanda', '250'],
  ['BL', 'Saint Barthélemy', '590'],
  ['SH', 'Saint Helena', '290'],
  ['KN', 'Saint Kitts and Nevis', '1869'],
  ['LC', 'Saint Lucia', '1758'],
  ['MF', 'Saint Martin', '590'],
  ['PM', 'Saint Pierre and Miquelon', '508'],
  ['VC', 'Saint Vincent and the Grenadines', '1784'],
  ['WS', 'Samoa', '685'],
  ['SM', 'San Marino', '378'],
  ['ST', 'São Tomé and Príncipe', '239'],
  ['SN', 'Senegal', '221'],
  ['SC', 'Seychelles', '248'],
  ['SL', 'Sierra Leone', '232'],
  ['SX', 'Sint Maarten', '1721'],
  ['SB', 'Solomon Islands', '677'],
  ['SO', 'Somalia', '252'],
  ['SS', 'South Sudan', '211'],
  ['LK', 'Sri Lanka', '94'],
  ['SD', 'Sudan', '249'],
  ['SR', 'Suriname', '597'],
  ['SJ', 'Svalbard and Jan Mayen', '47'],
  ['SY', 'Syria', '963'],
  ['TJ', 'Tajikistan', '992'],
  ['TZ', 'Tanzania', '255'],
  ['TL', 'Timor-Leste', '670'],
  ['TG', 'Togo', '228'],
  ['TK', 'Tokelau', '690'],
  ['TO', 'Tonga', '676'],
  ['TT', 'Trinidad and Tobago', '1868'],
  ['TM', 'Turkmenistan', '993'],
  ['TC', 'Turks and Caicos Islands', '1649'],
  ['TV', 'Tuvalu', '688'],
  ['UG', 'Uganda', '256'],
  ['UY', 'Uruguay', '598'],
  ['UZ', 'Uzbekistan', '998'],
  ['VU', 'Vanuatu', '678'],
  ['VA', 'Vatican City', '379'],
  ['VG', 'British Virgin Islands', '1284'],
  ['VI', 'U.S. Virgin Islands', '1340'],
  ['WF', 'Wallis and Futuna', '681'],
  ['EH', 'Western Sahara', '212'],
  ['YE', 'Yemen', '967'],
  ['ZM', 'Zambia', '260'],
  ['ZW', 'Zimbabwe', '263'],
]

export const PHONE_COUNTRIES: PhoneCountry[] = RAW.map(([iso, name, dial]) => ({
  iso,
  name,
  dial,
}))

export const DEFAULT_PHONE_COUNTRY_ISO = 'UA'

export function findPhoneCountryByIso(iso: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find((c) => c.iso === iso)
}

export function findPhoneCountryByDial(dial: string): PhoneCountry | undefined {
  const normalized = dial.replace(/\D/g, '')
  if (!normalized) return undefined
  return [...PHONE_COUNTRIES]
    .sort((a, b) => b.dial.length - a.dial.length)
    .find((c) => normalized.startsWith(c.dial) || c.dial === normalized)
}

/** Спроба розпізнати країну з повного номера (+…). */
export function matchPhoneCountryFromE164(e164: string): { country: PhoneCountry; local: string } | null {
  const digits = e164.replace(/\D/g, '')
  if (digits.length < 4) return null
  const country = findPhoneCountryByDial(digits)
  if (!country) return null
  const local = digits.slice(country.dial.length).replace(/^0+/, '')
  if (!local) return null
  return { country, local }
}
