ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "linkedProductIds" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "linkedCategoryIds" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "linkedIngredientIds" TEXT NOT NULL DEFAULT '[]';
