-- AlterTable SiteSetting
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "telegramUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "whatsappUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "restaurantPickupAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "freeDeliveryThreshold" DOUBLE PRECISION NOT NULL DEFAULT 1000;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 50;

-- AlterTable Order
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfillmentType" TEXT NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
