ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "authHeroPhone2VideoUrls" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "authHeroPhone1Copy" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "authHeroPhone2Copy" TEXT NOT NULL DEFAULT '{}';
